# Setup
title:        MoMEMta
tagline:      Modular Matrix Element Method implementation
baseurl:      ""
paginate:     1

author:
  name:       MoMEMta
  url:        http://momemta.github.io/

# Gems
gems:
  - jekyll-paginate
