site_name: MoMEMta
site_description: 'Modular Matrix Element Method implementation'
site_author: 'The MoMEMta team'
site_url: 'https://momemta.github.io'
site_dir: _site
google_analytics: ['UA-78443359-1', 'momemta.github.io']

extra:
  version: 'v0.1.0'
  logo: 'images/logo.png'
  palette:
    primary: 'blue grey'
    accent: 'teal'
  links:
    - 'Roadmap': 'https://trello.com/b/lQXfKafM/momemta-roadmap'
    - 'Technical documentation': 'https://momemta.github.io/MoMEMta/'
    - 'Contact us': mailto:momemta-contact@cern.ch

repo_name: 'GitHub'
repo_url: 'https://github.com/MoMEMta/MoMEMta'
 
theme_dir: 'mkdocs-material/material'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - mdx_math:
      enable_dollar_delimiter: true
      render_to_span: true
  - toc:
      permalink: '#'
  - footnotes

# MathJax
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML

extra_css:
  - css/extra.css

pages:
  - Main: index.md
  - What is MoMEMta?: introduction.md
  - Getting started: 'getting-started.md'
  - 'In depth':
    - 'Calling MoMEMta': 'in-depth/calling-momemta.md'
    - 'Configuration file': 'in-depth/configuration-file.md'
    - 'Validation': 'in-depth/validation.md'
  - 'Change log': 'changelog.md'
