site_name: MoMEMta
site_description: 'Modular Matrix Element Method implementation'
site_author: 'The MoMEMta team'
site_url: 'https://momemta.github.io'
site_dir: _site
google_analytics: ['UA-78443359-1', 'momemta.github.io']

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 the MoMEMta team'

extra:
  version: 'v1.0.0'
  social:
    - type: 'envelope'
      link: 'mailto:momemta-contact@cern.ch'
      title: 'Contact us'
    - type: 'book'
      link: 'https://momemta.github.io/MoMEMta/'
      title: 'Technical documentation'
    - type: 'map'
      link: 'https://trello.com/b/lQXfKafM/momemta-roadmap'
      title: 'Roadmap'

repo_name: 'GitHub'
repo_url: 'https://github.com/MoMEMta/MoMEMta'
edit_uri: null

theme:
    name: 'material'
    custom_dir: 'theme'
    logo: 'images/logo.svg'
    palette:
        primary: 'blue grey'
        accent: 'teal'

# Extensions
markdown_extensions:
  - codehilite
      #pygments_style: base16-eighties.dark
  - admonition
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
  - footnotes
  - meta

# MathJax
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra_css:
  - 'stylesheets/base16-eighties.dark.css'
  - 'stylesheets/momemta.css'

nav:
  - The MoMEMta project: index.md
  - What is MoMEMta?: introduction.md
  - Getting started: 'getting-started.md'
  - 'In depth':
    - 'Calling MoMEMta': 'in-depth/calling-momemta.md'
    - 'Configuration file': 'in-depth/configuration-file.md'
    - 'Parameters': 'in-depth/parameters.md'
    - 'Adding a new module': 'in-depth/new-module.md'
    - 'Validation': 'in-depth/validation.md'
  - 'Release notes': 'changelog.md'
  #- 'Acknowledgements': 'acknowledgement.md'
